# Generated by Django 5.2.6 on 2025-09-10 17:50

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Cliente',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('area', models.CharField(max_length=150, verbose_name='Área/Cliente')),
                ('localidade', models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidade')),
            ],
            options={
                'verbose_name': 'Cliente',
                'verbose_name_plural': 'Clientes',
                'ordering': ['area'],
            },
        ),
    ]
