# Generated by Django 5.2.6 on 2025-09-10 17:50

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Atividade',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('demanda', models.TextField(verbose_name='Demanda')),
                ('area_solicitante', models.CharField(blank=True, max_length=150, null=True, verbose_name='Área Solicitante')),
                ('responsaveis', models.TextField(blank=True, null=True, verbose_name='Responsáveis (separar por ;)')),
                ('data_solicitacao', models.DateField(blank=True, null=True, verbose_name='Data de Solicitação')),
                ('prazo', models.DateField(blank=True, null=True, verbose_name='Prazo')),
                ('urgencia', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=10, null=True, verbose_name='Urgência')),
                ('importancia', models.CharField(blank=True, choices=[('Alta', 'Alta'), ('Média', 'Média'), ('Baixa', 'Baixa')], max_length=10, null=True, verbose_name='Importância')),
                ('quadrante', models.CharField(blank=True, choices=[('Q1', 'Q1'), ('Q2', 'Q2'), ('Q3', 'Q3'), ('Q4', 'Q4')], max_length=2, null=True, verbose_name='Quadrante')),
                ('status', models.CharField(blank=True, choices=[('Não iniciado', 'Não iniciado'), ('Em andamento', 'Em andamento'), ('Concluído', 'Concluído')], max_length=20, null=True, verbose_name='Status')),
                ('observacoes', models.TextField(blank=True, null=True, verbose_name='Observações')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atualizado_em', models.DateTimeField(auto_now=True, verbose_name='Atualizado em')),
            ],
            options={
                'verbose_name': 'Atividade',
                'verbose_name_plural': 'Atividades',
                'ordering': ['-criado_em'],
            },
        ),
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.TextField(verbose_name='Comentário')),
                ('criado_em', models.DateTimeField(auto_now_add=True, verbose_name='Criado em')),
                ('atividade', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='comentarios', to='atividade.atividade', verbose_name='Atividade')),
            ],
            options={
                'verbose_name': 'Comentário',
                'verbose_name_plural': 'Comentários',
                'ordering': ['-criado_em'],
            },
        ),
    ]
