# Generated by Django 5.2.6 on 2025-09-11 16:55

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('atividade', '0001_initial'),
        ('cliente', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='atividade',
            name='cliente',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='atividades', to='cliente.cliente', verbose_name='Área/Cliente'),
        ),
        migrations.AddField(
            model_name='atividade',
            name='localidade',
            field=models.CharField(blank=True, max_length=150, null=True, verbose_name='Localidade'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='area_solicitante',
            field=models.CharField(blank=True, max_length=255, null=True, verbose_name='Área solicitante'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='data_solicitacao',
            field=models.DateField(blank=True, null=True, verbose_name='Data de solicitação'),
        ),
        migrations.AlterField(
            model_name='atividade',
            name='demanda',
            field=models.CharField(max_length=255, verbose_name='Demanda'),
        ),
    ]
